name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/data/assets/logo/logo.png
    - lib/data/assets/logo/
    - lib/data/assets/

  fonts:
    - family: Graphik
      fonts:
        - asset: lib/data/assets/fonts/Graphik-Regular.otf
          weight: 400
        - asset: lib/data/assets/fonts/Graphik-Semibold.otf
          weight: 500
        - asset: lib/data/assets/fonts/Graphik-Medium.otf
          weight: 600
